INSERT INTO lkup_cd_pitches VALUES ('+','following pickoff throw by catcher');
INSERT INTO lkup_cd_pitches VALUES ('*','the following pitch was blocked by the catcher');
INSERT INTO lkup_cd_pitches VALUES ('.','marker for play not involving the batter');
INSERT INTO lkup_cd_pitches VALUES ('1','pickoff throw to first');
INSERT INTO lkup_cd_pitches VALUES ('2','pickoff throw to second');
INSERT INTO lkup_cd_pitches VALUES ('3','pickoff throw to third');
INSERT INTO lkup_cd_pitches VALUES ('>','indicates a runner going on the pitch');
INSERT INTO lkup_cd_pitches VALUES ('B','ball');
INSERT INTO lkup_cd_pitches VALUES ('C','called strike');
INSERT INTO lkup_cd_pitches VALUES ('F','foul');
INSERT INTO lkup_cd_pitches VALUES ('H','hit batter');
INSERT INTO lkup_cd_pitches VALUES ('I','intentional ball');
INSERT INTO lkup_cd_pitches VALUES ('K','strike (unknown type)');
INSERT INTO lkup_cd_pitches VALUES ('L','foul bunt');
INSERT INTO lkup_cd_pitches VALUES ('M','missed bunt attempt');
INSERT INTO lkup_cd_pitches VALUES ('N','no pitch (on balks and interference calls)');
INSERT INTO lkup_cd_pitches VALUES ('O','foul tip on bunt');
INSERT INTO lkup_cd_pitches VALUES ('P','pitchout');
INSERT INTO lkup_cd_pitches VALUES ('Q','swinging on pitchout');
INSERT INTO lkup_cd_pitches VALUES ('R','foul ball on pitchout');
INSERT INTO lkup_cd_pitches VALUES ('S','swinging strike');
INSERT INTO lkup_cd_pitches VALUES ('T','foul tip');
INSERT INTO lkup_cd_pitches VALUES ('U','unknown or missed pitch');
INSERT INTO lkup_cd_pitches VALUES ('V','called ball because pitcher went to his mouth');
INSERT INTO lkup_cd_pitches VALUES ('X','ball put into play by batter');
INSERT INTO lkup_cd_pitches VALUES ('Y','ball put into play on pitchout');
