/* INDIVIDUAL_BATTING_GAMES */
/* Create new table with batting data for individual games */
DROP TABLE IF EXISTS individual_batting_games;

CREATE TABLE individual_batting_games (
  `BAT_ID` char(8) NOT NULL,
  `GAME_ID` char(12) NOT NULL,
  `YEAR_ID` year(4) NOT NULL,
  `AT_BATS` tinyint(2),
  `SLUGGING` float,
  `AVERAGE` float,
  `HITS` tinyint(2),
  `OBP` float,
  `PLATE_APPS` tinyint(2),
  `WALKS` tinyint(2) DEFAULT 0
) ENGINE=INNODB DEFAULT CHARSET=latin1 /*!50100 PARTITION BY LIST (YEAR_ID) (PARTITION p1 VALUES IN (1921) ENGINE = INNODB, PARTITION p2 VALUES IN (1922) ENGINE = INNODB, PARTITION p3 VALUES IN (1952) ENGINE = INNODB, PARTITION p4 VALUES IN (1953) ENGINE = INNODB, PARTITION p5 VALUES IN (1954) ENGINE = INNODB, PARTITION p6 VALUES IN (1955) ENGINE = INNODB, PARTITION p7 VALUES IN (1956) ENGINE = INNODB, PARTITION p8 VALUES IN (1957) ENGINE = INNODB, PARTITION p9 VALUES IN (1958) ENGINE = INNODB, PARTITION p10 VALUES IN (1959) ENGINE = INNODB, PARTITION p11 VALUES IN (1960) ENGINE = INNODB, PARTITION p12 VALUES IN (1961) ENGINE = INNODB, PARTITION p13 VALUES IN (1962) ENGINE = INNODB, PARTITION p14 VALUES IN (1963) ENGINE = INNODB, PARTITION p15 VALUES IN (1964) ENGINE = INNODB, PARTITION p16 VALUES IN (1965) ENGINE = INNODB, PARTITION p17 VALUES IN (1966) ENGINE = INNODB, PARTITION p18 VALUES IN (1967) ENGINE = INNODB, PARTITION p19 VALUES IN (1968) ENGINE = INNODB, PARTITION p20 VALUES IN (1969) ENGINE = INNODB, PARTITION p21 VALUES IN (1970) ENGINE = INNODB, PARTITION p22 VALUES IN (1971) ENGINE = INNODB, PARTITION p23 VALUES IN (1972) ENGINE = INNODB, PARTITION p24 VALUES IN (1973) ENGINE = INNODB, PARTITION p25 VALUES IN (1974) ENGINE = INNODB, PARTITION p26 VALUES IN (1975) ENGINE = INNODB, PARTITION p27 VALUES IN (1976) ENGINE = INNODB, PARTITION p28 VALUES IN (1977) ENGINE = INNODB, PARTITION p29 VALUES IN (1978) ENGINE = INNODB, PARTITION p30 VALUES IN (1979) ENGINE = INNODB, PARTITION p31 VALUES IN (1980) ENGINE = INNODB, PARTITION p32 VALUES IN (1981) ENGINE = INNODB, PARTITION p33 VALUES IN (1982) ENGINE = INNODB, PARTITION p34 VALUES IN (1983) ENGINE = INNODB, PARTITION p35 VALUES IN (1984) ENGINE = INNODB, PARTITION p36 VALUES IN (1985) ENGINE = INNODB, PARTITION p37 VALUES IN (1986) ENGINE = INNODB, PARTITION p38 VALUES IN (1987) ENGINE = INNODB, PARTITION p39 VALUES IN (1988) ENGINE = INNODB, PARTITION p40 VALUES IN (1989) ENGINE = INNODB, PARTITION p41 VALUES IN (1990) ENGINE = INNODB, PARTITION p42 VALUES IN (1991) ENGINE = INNODB, PARTITION p43 VALUES IN (1992) ENGINE = INNODB, PARTITION p44 VALUES IN (1993) ENGINE = INNODB, PARTITION p45 VALUES IN (1994) ENGINE = INNODB, PARTITION p46 VALUES IN (1995) ENGINE = INNODB, PARTITION p47 VALUES IN (1996) ENGINE = INNODB, PARTITION p48 VALUES IN (1997) ENGINE = INNODB, PARTITION p49 VALUES IN (1998) ENGINE = INNODB, PARTITION p50 VALUES IN (1999) ENGINE = INNODB, PARTITION p51 VALUES IN (2000) ENGINE = INNODB, PARTITION p52 VALUES IN (2001) ENGINE = INNODB, PARTITION p53 VALUES IN (2002) ENGINE = INNODB, PARTITION p54 VALUES IN (2003) ENGINE = INNODB, PARTITION p55 VALUES IN (2004) ENGINE = INNODB, PARTITION p56 VALUES IN (2005) ENGINE = INNODB, PARTITION p57 VALUES IN (2006) ENGINE = INNODB, PARTITION p58 VALUES IN (2007) ENGINE = INNODB, PARTITION p59 VALUES IN (2008) ENGINE = INNODB, PARTITION p60 VALUES IN (2009) ENGINE = INNODB, PARTITION p61 VALUES IN (2010) ENGINE = INNODB, PARTITION p62 VALUES IN (2011) ENGINE = INNODB, PARTITION p63 VALUES IN (2012) ENGINE = INNODB, PARTITION p64 VALUES IN (2013) ENGINE = INNODB, PARTITION p65 VALUES IN (2014) ENGINE = INNODB, PARTITION p66 VALUES IN (2015) ENGINE = INNODB, PARTITION p67 VALUES IN (2016) ENGINE = INNODB) */;

DROP TEMPORARY TABLE IF EXISTS tbl_atbats;
DROP TEMPORARY TABLE IF EXISTS tbl_walks;
DROP TEMPORARY TABLE IF EXISTS tbl_plateapps;

CREATE TEMPORARY TABLE IF NOT EXISTS tbl_atbats AS 
(SELECT BAT_ID, GAME_ID, YEAR_ID, COUNT(AB_FL) AS AT_BATS, SUM(H_CD)/COUNT(AB_FL) AS SLUGGING, SUM(HIT_CD)/COUNT(AB_FL) AS AVERAGE, SUM(HIT_CD) AS HITS FROM events 
WHERE AB_FL = 'T' AND YEAR_ID = 2016
GROUP BY BAT_ID, GAME_ID, YEAR_ID);

# SELECT * FROM tbl_atbats;

CREATE TEMPORARY TABLE IF NOT EXISTS tbl_walks AS 
(SELECT BAT_ID, GAME_ID, YEAR_ID, COUNT(EVENT_CD) AS WALKS FROM events 
WHERE (EVENT_CD > 13 AND EVENT_CD < 17) AND YEAR_ID = 2016
GROUP BY BAT_ID, GAME_ID, YEAR_ID);

# SELECT * FROM tbl_walks;

CREATE TEMPORARY TABLE IF NOT EXISTS tbl_plateapps AS 
(SELECT BAT_ID, GAME_ID, YEAR_ID, COUNT(BAT_EVENT_FL) AS PLATE_APPS FROM events 
WHERE BAT_EVENT_FL = 'T' AND YEAR_ID = 2016
GROUP BY BAT_ID, GAME_ID, YEAR_ID);

# SELECT * FROM tbl_plateapps;

INSERT INTO individual_batting_games (BAT_ID, GAME_ID, YEAR_ID, AT_BATS, SLUGGING, AVERAGE, HITS, OBP, PLATE_APPS, WALKS)
SELECT ab.BAT_ID, ab.GAME_ID, ab.YEAR_ID, ab.AT_BATS, ab.SLUGGING, ab.AVERAGE, ab.HITS, (ab.HITS + IFNULL(w.WALKS, 0))/pa.PLATE_APPS AS OBP, pa.PLATE_APPS, IFNULL(w.WALKS, 0)
FROM tbl_atbats ab
LEFT JOIN tbl_walks w
ON w.GAME_ID = ab.GAME_ID AND w.BAT_ID = ab.BAT_ID
INNER JOIN tbl_plateapps pa
ON pa.GAME_ID = ab.GAME_ID AND pa.BAT_ID = ab.BAT_ID;

DROP TEMPORARY TABLE IF EXISTS tbl_atbats;
DROP TEMPORARY TABLE IF EXISTS tbl_walks;
DROP TEMPORARY TABLE IF EXISTS tbl_plateapps;
