CREATE VIEW `season_summaries` AS
SELECT TEAM_ID,
	YEAR_ID,
	SUM(IF(SCORE_CT > OPP_SCORE_CT, 1, 0)) AS WIN_CT,
    SUM(IF(SCORE_CT < OPP_SCORE_CT, 1, 0)) AS LOSS_CT,
    SUM(SCORE_CT) AS TOTAL_RUNS, 
	SUM(HITS_CT) AS TOTAL_HITS,
    SUM(ERR_CT) AS TOTAL_ERRORS,
    SUM(LOB_CT) AS TOTAL_LOB,
    SUM(OPP_SCORE_CT) AS TOTAL_OPP_RUNS, 
	SUM(OPP_HITS_CT) AS TOTAL_OPP_HITS,
    SUM(OPP_ERR_CT) AS TOTAL_OPP_ERRORS,
    SUM(OPP_LOB_CT) AS TOTAL_OPP_LOB,
    (SUM(SCORE_CT) - SUM(OPP_SCORE_CT)) AS RUN_DIFFERENTIAL
FROM (
	SELECT HOME_TEAM_ID AS TEAM_ID,
		YEAR_ID,
		HOME_SCORE_CT AS SCORE_CT, 
        HOME_HITS_CT AS HITS_CT, 
        AWAY_SCORE_CT AS OPP_SCORE_CT,
        HOME_ERR_CT AS ERR_CT,
        HOME_LOB_CT AS LOB_CT,
        AWAY_ERR_CT AS OPP_ERR_CT,
        AWAY_HITS_CT AS OPP_HITS_CT,
        AWAY_LOB_CT AS OPP_LOB_CT
	FROM games
	UNION ALL
	SELECT AWAY_TEAM_ID AS TEAM_ID,
		YEAR_ID,
		AWAY_SCORE_CT AS SCORE_CT, 
        AWAY_HITS_CT AS HITS_CT, 
        HOME_SCORE_CT AS OPP_SCORE_CT,
        AWAY_ERR_CT AS ERR_CT,
        AWAY_LOB_CT AS LOB_CT,
        HOME_ERR_CT AS OPP_ERR_CT,
        HOME_HITS_CT AS OPP_HITS_CT,
        HOME_LOB_CT AS OPP_LOB_CT
	FROM games
) t
GROUP BY TEAM_ID, YEAR_ID;